#!/usr/bin/env node

const path = require('path');
const { readFile } = require('fs/promises');
const git = require('simple-git')();
const git_changelog = require('git-changelog/tasks/git_changelog_generate');

const currentDir = process.cwd();
const configPath = path.join(currentDir, 'package.json');

function readConfig(configPath) {
  return readFile(configPath)
    .then(json => JSON.parse(json))
    .catch((error) => {
      git_changelog.log('error', error.message);

      return {
          input: './spec.json',
          output: './client',
      }
    });
}

git_changelog.log('info', `\nTrying to generate changelog....\n`);

Promise.all([
  git.tags(), 
  readConfig(configPath)
])
  .then(([tags, info]) => {
    const { all = [], latest } = tags;
    const { version, name, description, repository } = info;
    const tag = all[all.length - 2] || latest
    const template = path.join('changelog', 'template.md')
    const options = {
      tag,
      version_name: version,
      app_name: name,
      intro: description,
      repo_url: repository,
      template,
      provider: 'github',
      logo: 'https://cdn1.iconfinder.com/data/icons/just-for-fun/64/__notification_messege_alarm-512.png',
    };

    return [git_changelog.generate(options, true), options];
  })
  .then(({ name, version }) =>
    git_changelog.log('success', `Successfully generated changelog for ${name} v${version}`),
  )